#
# This file was created by Xilinx Vitis tool.
#


#
# tools
#

RM = rm -f
RMDIR = rm -rf

#
# variables
#

SDCARD_GEN = sdcard_gen
GENERATE_BIF = ::scw::generate_bif

XPFM_PATH = D:/VitisWorkspace/fft_dma/export/fft_dma/fft_dma.xpfm
SYS_CONFIG = fft_dma
DOMAINS = standalone_domain
BIF_PATH = D:/VitisWorkspace/full_fft_system/Debug/system.bif

BITSTREAM_PATH = D:/VitisWorkspace/full_fft/_ide/bitstream/fft_dma.bit
SD_FILES = --elf D:/VitisWorkspace/full_fft/Debug/full_fft.elf,ps7_cortexa9_0

#
# primary build targets
#

all: sd_card

sd_card:
	-@echo Generating bif file for the system project
	generate_system_bif.bat 52819 ${XPFM_PATH} ${DOMAINS} ${BIF_PATH}
	${SDCARD_GEN} --xpfm ${XPFM_PATH} --sys_config ${SYS_CONFIG} --bif ${BIF_PATH} --bitstream ${BITSTREAM_PATH} ${SD_FILES}

clean:
	$(RMDIR) ./_sds
	${RMDIR} sd_card
	${RM} system.bif

.PHONY: all sd_card clean


